version: '3.9'

services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.3.6
    # M1チップでも動くように
    platform: linux/x86_64
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      # AWS_ACCESS_KEY_IDとAWS_SECRET_ACCESS_KEYを環境変数として使用
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # MFAを使うため、AWS_SESSION_TOKENも環境変数として使用
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
# 永続Volumeを作成
volumes:
  infra:
