# Generated by Django 4.2.8 on 2023-12-24 06:39

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import application.utils.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_comment="システムユーザID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        db_comment="社員番号",
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[0-9]{8}$")
                        ],
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_comment="ユーザ名",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="メールアドレス", max_length=254, unique=True
                    ),
                ),
                (
                    "role",
                    models.PositiveIntegerField(
                        choices=[(0, "管理者"), (1, "一般")],
                        db_comment="システムユーザのロール",
                        default=0,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日"),
                ),
                (
                    "is_verified",
                    models.BooleanField(db_comment="有効化有無", default=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="作成者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_comment="更新者",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "User",
                "db_table_comment": "システムユーザ",
                "ordering": ["employee_number"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(db_comment="都道府県", max_length=255),
                ),
                (
                    "municipalities",
                    models.CharField(db_comment="市区町村", max_length=255),
                ),
                (
                    "house_no",
                    models.CharField(db_comment="丁・番地", max_length=255),
                ),
                (
                    "other",
                    models.CharField(
                        blank=True, db_comment="その他(マンション名など)", max_length=255
                    ),
                ),
                (
                    "post_no",
                    models.CharField(
                        db_comment="郵便番号",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{7}$", "7桁の数字を入力してください。"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "Address",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kana", models.CharField(db_comment="カナ氏名", max_length=255)),
                ("name", models.CharField(db_comment="氏名", max_length=255)),
                ("birthday", models.DateField(db_comment="誕生日")),
                (
                    "email",
                    models.EmailField(db_comment="メールアドレス", max_length=254),
                ),
                (
                    "phone_no",
                    models.CharField(
                        blank=True,
                        db_comment="電話番号",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{11}$", "11桁の数字を入力してください。"
                            )
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日時"),
                ),
                (
                    "address",
                    models.OneToOneField(
                        db_comment="住所のFK",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="application.address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="作成者ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_comment="更新者ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Customer",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="商品ID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_comment="商品名", max_length=255)),
                ("details", models.TextField(blank=True, db_comment="商品の詳細")),
                (
                    "price",
                    models.PositiveIntegerField(db_comment="商品の金額", default=0),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_comment="更新日"),
                ),
            ],
            options={
                "db_table": "Product",
                "db_table_comment": "商品",
            },
        ),
        migrations.CreateModel(
            name="UserResetPassword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="システムユーザID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_comment="パスワード設定メールURL用トークン", max_length=255
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(
                        db_comment="有効期限", default=None, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "is_used",
                    models.BooleanField(db_comment="使用有無", default=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="ユーザテーブル外部キー",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_password_reset",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "PasswordReset",
                "db_table_comment": "ユーザパスワード再設定",
            },
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="システムユーザID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_comment="ユーザ招待用メールURL用トークン", max_length=255
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(
                        db_comment="有効期限", default=None, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "is_used",
                    models.BooleanField(db_comment="使用有無", default=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="社員テーブル外部キー",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Invitation",
                "db_table_comment": "ユーザ招待用",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        db_comment="お客様の画像データ",
                        storage=application.utils.storages.CustomStorage(),
                        upload_to="customer_photo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="作成者ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        db_comment="お客様ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_photo",
                        to="application.customer",
                    ),
                ),
            ],
            options={
                "db_table": "Photo",
            },
        ),
    ]
