# Generated by Django 4.2.7 on 2023-12-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.OneToOneField(
                db_comment="住所のFK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="application.address",
            ),
        ),
    ]
