# Generated by Django 4.2.5 on 2023-11-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveIntegerField(
                choices=[(0, "管理者"), (1, "一般"), (2, "アルバイト")],
                db_comment="システムユーザのロール",
                default=2,
            ),
        ),
    ]
