# Generated by Django 4.2.8 on 2024-01-09 05:31

import application.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", application.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ForeignKey(
                db_comment="システム利用者権限テーブルの外部キー",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="auth.group",
            ),
            preserve_default=False,
        ),
    ]
