# Generated by Django 4.2.7 on 2023-12-07 12:20

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_alter_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="house_no",
            field=models.CharField(db_comment="丁・番地", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                db_comment="ID",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="municipalities",
            field=models.CharField(db_comment="市区町村", max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="other",
            field=models.CharField(
                blank=True, db_comment="その他(マンション名など)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="post_no",
            field=models.CharField(
                db_comment="郵便番号",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{7}$", "7桁の数字を入力してください。"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="prefecture",
            field=models.CharField(db_comment="都道府県", max_length=255),
        ),
    ]
