# Generated by Django 4.2.5 on 2023-10-21 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_userresetpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(db_comment="有効化有無", default=False),
        ),
        migrations.AlterField(
            model_name="userresetpassword",
            name="user",
            field=models.ForeignKey(
                db_comment="社員テーブル外部キー",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_password_reset",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="userresetpassword",
            table="user_password_reset",
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="システムユーザID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_comment="パスワード設定メールURL用トークン", max_length=255
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(
                        db_comment="有効期限", default=None, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="社員テーブル外部キー",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_invitation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_password_setting",
                "db_table_comment": "社員パスワード再設定",
            },
        ),
    ]
