# Generated by Django 4.2.8 on 2023-12-20 00:52

import application.utils.storages
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "application",
            "0004_customer_created_at_customer_created_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="ID",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        db_comment="お客様の画像データ",
                        storage=application.utils.storages.CustomStorage(),
                        upload_to="customer_photo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="作成時間"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        db_comment="お客様ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_photo",
                        to="application.customer",
                    ),
                ),
            ],
            options={
                "db_table": "Photo",
            },
        ),
    ]
