# Generated by Django 4.2.8 on 2023-12-20 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="created_by",
            field=models.ForeignKey(
                db_comment="作成者ID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
