name: Enable Branch Protection Rules
on: workflow_dispatch
# on: create

jobs:
  Setup:
    name: Enable Branch Protection Rules
    runs-on: ubuntu-20.04
    steps:
      # if [ "${{ matrix.branch }}" == 'develop' ]
      # then
      #   REQUIRED_APPROVING_REVIEW_COUNT=1
      # elif [ "${{ matrix.branch }}" == 'main' ]
      # then
      #   REQUIRED_APPROVING_REVIEW_COUNT=2
      - name: Execute API
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.BRANCH_PROTECTION_API_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/branches/develop/protection \
          -d '{"required_status_checks":{"strict":false,"contexts":[]},"enforce_admins":null,"required_pull_request_reviews":{"dismiss_stale_reviews":false,"require_code_owner_reviews":false,"required_approving_review_count":1,"require_last_push_approval":false},"restrictions":null,"required_conversation_resolution":true}'
      - name: Execute Branch Protection Rule API for main
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.BRANCH_PROTECTION_API_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{"required_status_checks":{"strict":false,"contexts":[]},"enforce_admins":null,"required_pull_request_reviews":{"dismiss_stale_reviews":false,"require_code_owner_reviews":false,"required_approving_review_count":2,"require_last_push_approval":false},"restrictions":null,"required_conversation_resolution":true}'
